### PR TITLE
Add support for offline response scanning

### PR DESCRIPTION
**Pull request by confuciussayuhm**
# Pull Request Template

## Description
This PR introduces offline analysis capabilities to humble.py, allowing users to analyze HTTP headers from raw response files without making live requests. This enhancement makes the tool more versatile, especially useful for analyzing historical responses or working in environments with limited connectivity.

Key changes:
- Added new `-if/--input-file` parameter for offline analysis
- Implemented `parse_offline_headers()` to process raw HTTP response files
- Created `determine_scheme_safety()` for better URL scheme validation
- Added `get_display_url()` for consistent URL representation
- Enhanced error handling for invalid URLs and file processing
- Updated documentation and help text to reflect new functionality

Fixes # (no specific issue referenced)

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
Tests performed to verify the changes include:

- [x] Offline Analysis Testing
  - Tested with valid HTTP response files containing various header combinations
  - Verified parsing of status codes and headers from raw response files
  - Validated error handling for malformed input files

- [x] URL Handling Testing
  - Tested URL scheme safety validation with HTTP/HTTPS URLs
  - Verified handling of invalid URLs and empty URL scenarios
  - Confirmed proper display of URLs in analysis output

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
  - Added docstrings for new functions
  - Included detailed comments explaining offline analysis logic
- [x] I have made corresponding changes to the documentation
  - Updated help text and usage information
  - Added documentation for new command line parameters
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by rfc-st** [comment]
Hi, @confuciussayuhm 

First all thanks for this PR and for your time!. I have a few comments (the first ones that come to mind) related to it:

- When you mention “_raw response files_” do you mean the possibility to have a text file, with certain HTTP response headers like of the following image, and parse it with '_humble_' via the proposed new parameters? (this is an example of the headers of google): https://imgur.com/a/HqKpGj0. This text file should have a specific format to parse it correctly?, do you have any concrete example?

- If this is what you want, and reviewing your PR, the HTTP response header analysis in '_humble_' is based on the following functions and logic: print_missing_headers(), check_frame_options(), get_fingerprint_headers(), print_fingerprint_headers(), 
, all checks based on the URL requests library response (identified with the comment “_# Section '3. Deprecated HTTP Response Headers/Protocols and Insecure Values_')”, print_empty_headers() and print_browser_compatibility(). All of them must be taken into account when analyzing HTTP response headers.

- In order to correctly display and calculate the statistics of the analysis performed (parameter '-a'), it is required that the analysis performed has a URL associated with it. Ex: function url_analytics()

- Similarly, certain insecure header checks require knowledge of the scheme (http:// or https://) of the URL being analyzed.

Let's do the following: please show me some examples of "_raw response files_" and I will investigate how to integrate their parsing into '_humble_': the files must include request status codes and the parsed URL to which those HTTP response headers correspond.

Thanks!

**Comment by rfc-st** [comment]
Hi, @confuciussayuhm

Cool!.

Let me look into the specific format of curl and Burp Suite responses (and maybe, why not?, other tools!) when requesting the HTTP response headers of a URL; to parse and analyze them in '_humble_' (HTTP status code, URL and HTTP header/Value).

Great suggestion!, I'll keep you posted in this thread.

Thanks.


Best regards,

**Comment by rfc-st** [comment]
Hi @confuciussayuhm,

Please do a '_git pull_' to get the latest changes:

- New '-_if_' parameter: analyzes the HTTP response headers, and their values, from a text file.
- Including check that the file from the previous point exists.
- Created messages in English and Spanish, about various errors that may arise when processing this file.
-  And, of course, [mentioning](https://github.com/rfc-st/humble/?tab=readme-ov-file#acknowledgements) you!

Try these changes, please ... and if you miss anything, let me know in this thread.

Thanks!.

Regards,

**Comment by confuciussayuhm** [comment]
Looking good man! Thanks for the addition!

**Pull request closed without merging**
