### PR TITLE
Debian/ParrotOS .deb package for Humble

### PR DESCRIPTION
**Pull request by danterolle**
## Description

I added a configuration to create a .deb package that is easily deployable on Debian-based distributions (e.g., ParrotOS). Once the user is interested in installing Humble, and the package is uploaded to the repositories of the desired distribution, simply type `sudo apt install humble` (or similar).

I had to modify Humble's source code slightly, due to a path problem, as previously relative paths were used for templates and static files, and after the package build, since these files are placed in `/usr/share/humble`, they were not found, and this was clearly an error that prevented the program from running. 

However, I solved it by adding a few lines of code to find and read the absolute path of these files, and in this way the program works as before, only now it does not show any errors when installed via `apt` package manager.

Screenshot 2024-08-26 alle 12 39 36

If this PR is accepted, I will request on behalf of the ParrotOS team to upload the package to our repositories. Also, Humble works on ARM platforms.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Download this repository, install in your Debian distribution the essential tools to build a Debian package (build-essential, devscripts, etc...). It is important to consider the project's python dependencies (and possibly install them, see the `debian/control` file). 

Then, create an `.orig.tar.xz` file using the appropriate tar command (with `czf` switches) from the Humble folder: `tar czf humble_0.1.orig.tar.gz humble/`

After that, to start the build, just type in a terminal window `debuild -us -uc` and a new .deb file will be created in a few seconds.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by rfc-st** [comment]
Hello,

Thank you for your PR and your time.

As we have spoken privately, I leave this PR on hold: I have to calmly review its content and possible impact on other distributions.

We will keep in touch!.

Best regards.

**Comment by rfc-st** [comment]
Hello @danterolle,

I haven't forgotten about this :)!. Please check the commit https://github.com/rfc-st/humble/commit/88a4e5e930083801b0ea2f4ab5f51730f72c9ebf ... I have mentioned you in https://github.com/rfc-st/humble/?tab=readme-ov-file#acknowledgements.

I hope that with this change I cover your suggestion about absolute paths; about the rest of the changes you propose, I am still reviewing them.

Thank you!.

Best regards.

**Comment by danterolle** [comment]
Hello @rfc-st! 

Thanks a lot, if you think there are more changes needed (especially in the debian folder), let me know. I'll be happy to contribute!

**Comment by rfc-st** [comment]
Hi @danterolle:

First of all: Thank you!

I currently don't have time to check incompatibilities between ParrotOS and other distributions; my time is very limited. So let me keep thinking about the best strategy to make 'humble' available ... and let's keep talking.

Regards,

**Comment by danterolle** [comment]
I have closed this PR, I will open another one regarding **only** packaging in Debian, so that Humble will be compatible with any Debian-based distribution. Thanks.

**Pull request closed without merging**
